version: '2.1'
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Build
          command: ./gradlew build -x test
      - run:
          name: Test
          command: ./gradlew test
workflows:
  checkout-build-test:
    jobs:
      - build-and-test